#zuul:
#  prefix: /
##  routes:
##    eureka-server:
##      path: /server/**
##      url: http://localhost:8761
##    sleuth-client:
##      path: /client/**
##      service-id: SLEUTH-CLIENT
#      
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost
#      
#server:
#  port: 8083
#  
#spring:
#  application:
#    name: zuul-api-gateway
#  